-- Generated by Oracle SQL Developer Data Modeler 3.1.0.691
--   at:        2022-05-07 12:17:29 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE Blokady 
    ( 
     Id_blokady INTEGER NOT NULL,
     Data_rozpoczecia DATE  NOT NULL , 
     Data_zakonczenia DATE  NOT NULL , 
     Powod TEXT  NOT NULL , 
     Uzytkownicy_Id_uzytkownika INTEGER  NOT NULL 
    ) 
;


CREATE INDEX Relation_3 ON Blokady 
    ( 
     Uzytkownicy_Id_uzytkownika ASC 
    ) 
;


CREATE TABLE Komentarze 
    ( 
     Id_komentarza INTEGER  NOT NULL AUTO_INCREMENT , 
     Tresc TEXT  NOT NULL , 
     Data_dodania DATE  NOT NULL , 
     Uzytkownicy_Id_uzytkownika INTEGER  NOT NULL , 
     Memy_Id_mema INTEGER  NOT NULL , 
     Komentarze_Id_komentarza INTEGER 
    ) 
;


CREATE INDEX Relation_11 ON Komentarze 
    ( 
     Komentarze_Id_komentarza ASC 
    ) 
;
CREATE INDEX Relation_13 ON Komentarze 
    ( 
     Memy_Id_mema ASC 
    ) 
;
CREATE INDEX Relation_2 ON Komentarze 
    ( 
     Uzytkownicy_Id_uzytkownika ASC 
    ) 
;

ALTER TABLE Komentarze 
    ADD CONSTRAINT Komentarze_PK PRIMARY KEY ( Id_komentarza ) ;


CREATE TABLE Memy 
    ( 
     Id_mema INTEGER  NOT NULL AUTO_INCREMENT, 
     Nazwa_pliku TEXT  NOT NULL , 
     Data_dodania DATE  NOT NULL , 
     Uzytkownicy_Id_uzytkownika INTEGER  NOT NULL,
     Tytul TEXT  NOT NULL,
     Opis TEXT  NOT NULL,
     Kategoria TEXT  NOT NULL
    ) 
;


CREATE INDEX Relation_1 ON Memy 
    ( 
     Uzytkownicy_Id_uzytkownika ASC 
    ) 
;

ALTER TABLE Memy 
    ADD CONSTRAINT Memy_PK PRIMARY KEY ( Id_mema ) ;


CREATE TABLE Oceny_komentarzy 
    ( 
     Jaka_ocena SMALLINT  NOT NULL , 
     Uzytkownicy_Id_uzytkownika INTEGER  NOT NULL , 
     Komentarze_Id_komentarza INTEGER  NOT NULL 
    ) 
;


CREATE INDEX Relation_8 ON Oceny_komentarzy 
    ( 
     Uzytkownicy_Id_uzytkownika ASC 
    ) 
;
CREATE INDEX Relation_9 ON Oceny_komentarzy 
    ( 
     Komentarze_Id_komentarza ASC 
    ) 
;


CREATE TABLE Oceny_memow 
    ( 
     Jaka_ocena SMALLINT  NOT NULL , 
     Uzytkownicy_Id_uzytkownika INTEGER  NOT NULL , 
     Memy_Id_mema INTEGER  NOT NULL 
    ) 
;


CREATE INDEX Relation_5 ON Oceny_memow 
    ( 
     Uzytkownicy_Id_uzytkownika ASC 
    ) 
;
CREATE INDEX Relation_6 ON Oceny_memow 
    ( 
     Memy_Id_mema ASC 
    ) 
;


CREATE TABLE Uzytkownicy 
    ( 
     Id_uzytkownika INTEGER  NOT NULL AUTO_INCREMENT, 
     Login TEXT  NOT NULL , 
     Haslo TEXT  NOT NULL ,
     Email TEXT  NOT NULL,
     Typ_uzytkownika SMALLINT  NOT NULL , 
     Data_dolaczenia DATE  NOT NULL 
    ) 
;



ALTER TABLE Uzytkownicy 
    ADD CONSTRAINT Uzytkownicy_PK PRIMARY KEY ( Id_uzytkownika ) ;


CREATE TABLE Zgloszenia_komentarzy 
    ( 
     Id_zgloszenia INTEGER  NOT NULL AUTO_INCREMENT, 
     Tresc TEXT  NOT NULL , 
     Czy_rozpatrzony BOOLEAN  NOT NULL , 
     Komentarze_Id_komentarza INTEGER  NOT NULL , 
     Uzytkownicy_Id_uzytkownika INTEGER  NOT NULL 
    ) 
;


CREATE INDEX Relation_18 ON Zgloszenia_komentarzy 
    ( 
     Komentarze_Id_komentarza ASC 
    ) 
;
CREATE INDEX Relation_20 ON Zgloszenia_komentarzy 
    ( 
     Uzytkownicy_Id_uzytkownika ASC 
    ) 
;

ALTER TABLE Zgloszenia_komentarzy 
    ADD CONSTRAINT Id_komentarzy_PK PRIMARY KEY ( Id_zgloszenia ) ;


CREATE TABLE Zgloszenia_memow 
    ( 
     Id_zgloszenia INTEGER  NOT NULL AUTO_INCREMENT, 
     Tresc TEXT  NOT NULL , 
     Czy_rozpatrzony BOOLEAN  NOT NULL , 
     Memy_Id_mema INTEGER  NOT NULL , 
     Uzytkownicy_Id_uzytkownika INTEGER  NOT NULL 
    ) 
;


CREATE INDEX Relation_17 ON Zgloszenia_memow 
    ( 
     Memy_Id_mema ASC 
    ) 
;
CREATE INDEX Relation_19 ON Zgloszenia_memow 
    ( 
     Uzytkownicy_Id_uzytkownika ASC 
    ) 
;

ALTER TABLE Zgloszenia_memow 
    ADD CONSTRAINT Zgloszenia_PK PRIMARY KEY ( Id_zgloszenia ) ;

ALTER TABLE Blokady 
    ADD CONSTRAINT Blokady_PK PRIMARY KEY ( Id_blokady ) ;











-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                            13
-- ALTER TABLE                              5
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE STRUCTURED TYPE                   0
-- CREATE COLLECTION TYPE                   0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
